### ISSUE TITLE
Error: cannot find module 'fibers'

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#353]
I've been struggling with this problem for a long time now.
On Windows 10, with a fresh install of Meteor (v. 1.4.2.3), I try to install the meteorkitchen GUI with

meteor-kitchen ./meteor-kitchen.json kitchen2

I use the newest version of meteor-kitchen (downloaded yesterday) - v. 0.9.71.

I then get this error, when I try to run the meteor-kitchen GUI:

W20161220-07:29:47.774(1)? (STDERR) module.js:327
W20161220-07:29:47.775(1)? (STDERR)     throw err;
W20161220-07:29:47.776(1)? (STDERR)     ^
W20161220-07:29:47.778(1)? (STDERR)
W20161220-07:29:47.780(1)? (STDERR) Error: Cannot find module 'fibers'
W20161220-07:29:47.782(1)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20161220-07:29:47.783(1)? (STDERR)     at Function.Module._load (module.js:276:25)
W20161220-07:29:47.785(1)? (STDERR)     at Module.require (module.js:353:17)
W20161220-07:29:47.787(1)? (STDERR)     at require (internal/module.js:12:17)
W20161220-07:29:47.789(1)? (STDERR)     at Object.<anonymous> (D:\meteor\kitchen2\.meteor\local\build\programs\server\boot.js:1:75)
W20161220-07:29:47.792(1)? (STDERR)     at Module._compile (module.js:409:26)
W20161220-07:29:47.796(1)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20161220-07:29:47.798(1)? (STDERR)     at Module.load (module.js:343:32)
W20161220-07:29:47.800(1)? (STDERR)     at Function.Module._load (module.js:300:12)
W20161220-07:29:47.802(1)? (STDERR)     at Module.require (module.js:353:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

Any ideas?

**Comment by perak** [comment]
Doesn't happen on Mac and Linux. Did you tried simply `meteor npm install fibers`?

**Comment by xauxatz** [comment]
Hi - yes, I tried this and many many other things, including 
uninstalling, reinstalling various elements, rebooting, etc.

I actually fixed it now. While searching around I discovered other with 
similar problems (but unrelated to meteorkitchen).

So in fact meteorkitchen v. 0.9.71 does not work with meteor 1.4.2.3 on 
Windows 10.

It has to do with fibers, babel-runtime and npm - but other than that I 
don't know why.

If I run meteor with --release 1.4.1.3 it works. So it is necessary to 
downgrade.
